# Get all data from a variable for all instruments on a Site

This script pull data from the AODN geoserver service, composing the adequate query. It will have the data from the following collections:

1. Mooring temp/sal loggers: anmn_ts_timeseries_data
2. WQM instruments burst average: anmn_burst_avg_timeseries
3. CTD profiles: anmn_ctd_profiles

The `site_code` variable needs to be specified. All available data will be pulled, no time filter implemented here (although possible).

In [26]:
import codecs
import time
import pandas as pd


# The URL to the collection (as comma-separated values).
collection_url = "http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_ts_timeseries_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=(TIME%20AFTER%202018-01-01T00:00:00%20AND%20site_code%20LIKE%20'NRSROT')"

t0 = time.perf_counter()

# Fetch data...
data = pd.read_csv(collection_url)

t1 = time.perf_counter()

print(t1-t0)

data.head()

36.758237018002546

,FID,timeseries_id,index,site_code,platform_code,deployment_code,instrument_nominal_depth,TIME,TIME_quality_control,LATITUDE,...,PRES_quality_control,PRES_REL,PRES_REL_quality_control,geom,depth_b,sea_water_temperature_b,sea_water_electrical_conductivity_b,sea_water_salinity_b,sea_water_pressure_b,sea_water_pressure_due_to_sea_water_b
0,anmn_ts_timeseries_data.fid-2e7be01d_16a57e728...,23139,0,NRSROT,NRSROT,NRSROT-1804,27,2018-04-06T08:00:00,NaN,-31.9896,...,NaN,NaN,NaN,POINT (115.3853833333 -31.9895833333),True,True,False,False,False,False
1,anmn_ts_timeseries_data.fid-2e7be01d_16a57e728...,23139,1,NRSROT,NRSROT,NRSROT-1804,27,2018-04-06T08:10:00,NaN,-31.9896,...,NaN,NaN,NaN,POINT (115.3853833333 -31.9895833333),True,True,False,False,False,False
2,anmn_ts_timeseries_data.fid-2e7be01d_16a57e728...,23139,2,NRSROT,NRSROT,NRSROT-1804,27,2018-04-06T08:20:00,NaN,-31.9896,...,NaN,NaN,NaN,POINT (115.3853833333 -31.9895833333),True,True,False,False,False,False
3,anmn_ts_timeseries_data.fid-2e7be01d_16a57e728...,23139,3,NRSROT,NRSROT,NRSROT-1804,27,2018-04-06T08:30:00,NaN,-31.9896,...,NaN,NaN,NaN,POINT (115.3853833333 -31.9895833333),True,True,False,False,False,False
4,anmn_ts_timeseries_data.fid-2e7be01d_16a57e728...,23139,4,NRSROT,NRSROT,NRSROT-1804,27,2018-04-06T08:40:00,NaN,-31.9896,...,NaN,NaN,NaN,POINT (115.3853833333 -31.9895833333),True,True,False,False,False,False